---
- name: uWsgi | (apt) Install required system packages.
  apt: >
    pkg={{item}}
    state=present
    update-cache=yes
  with_items:
    - build-essential
    - python-dev
    - python-setuptools
    - python-psycopg2
    - python-pip

- name: uWsgi | install python-virtualenv with specific version
  apt: name="python-virtualenv={{ version.virtualenv }}*"  update_cache=yes  state=present force=yes
